# Generated by Django 4.2.1 on 2023-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='sponsors',
            field=models.ManyToManyField(to='main_app.sponsor'),
        ),
    ]
